name: gridded_pageview
description: A simple widget that displays children in a grid and multiple pages.
version: 0.1.0
homepage: https://github.com/Siarl/gridded_pageview
author: Wilkin van Roosmalen <w.s.roosmalen@gmail.com>

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  page_indicator: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
